describe('test register', () => {
  beforeEach(() => {
    cy.visit('http://localhost:3000/register')
  })
  it('TC1-1: all empty string', () => {
    cy.get('[id="register_submit"]').click()

    cy.contains('Invalid email').should('be.visible')
    cy.contains('Password must be at least 8 characters').should('be.visible')
    cy.contains('Invalid email').should('be.visible')
    cy.contains('Please fill both first and last name').should('be.visible')
    cy.contains('Fill display name').should('be.visible')
    cy.contains('Please fill valid phone number').should('be.visible')
    cy.contains('Invalid date').should('be.visible')
    cy.contains('Please select gender').should('be.visible')
    cy.contains('Please select your account role').should('be.visible')
    cy.url().should('eq', 'http://localhost:3000/register')
    cy.wait(5000)
  })
  it('TC1-2: all invalid', () => {
    cy.get('[name="email"]').type('012345678901234567890123456789012345678901234567890123456789@gmail.com')
    cy.get('[name="password"]').type('abcdefghijklmnopqrstuvwxyz0123456789')
    cy.get('[name="confirmPassword"]').type('abcdefghijklmnopqrstuvwxyz0123456789')
    cy.get('[name="firstName"]').type('himyfirstnameissomchaidoyouknowwhoami')
    cy.get('[name="lastName"]').type('mylastnameismaiborkfinditifyoucan')
    cy.get('[name="displayName"]').type('print(mydisplayname)ifyouwanttoknow')
    cy.get('[name="phoneNumber"]').type('123456789a')
    cy.get('[name="birthDate"]').type('9999-04-18')
    cy.get('[name="gender"][value="Male"]').check()
    cy.get('[name="role"][value="Customer"]').check()
    cy.get('[id="register_submit"]').click()

    cy.contains('Please fill both first and last name').should('be.visible')
    cy.contains('Your display name should not exceed 32 characters').should('be.visible')
    cy.contains('Please fill valid phone number').should('be.visible')
    cy.contains('Future date is not accepted').should('be.visible')
    cy.url().should('eq', 'http://localhost:3000/register')
    cy.wait(5000)
  })
  it('TC1-3: password and confirmPassword do not match', () => {
    cy.get('[name="email"]').type('provider@test.gg')
    cy.get('[name="password"]').type('123456789')
    cy.get('[name="confirmPassword"]').type('987654321')
    cy.get('[name="firstName"]').type('firstname')
    cy.get('[name="lastName"]').type('lastname')
    cy.get('[name="displayName"]').type('displayname')
    cy.get('[name="phoneNumber"]').type('0000000000')
    cy.get('[name="birthDate"]').type('2000-02-20')
    cy.get('[name="gender"][value="Male"]').check()
    cy.get('[name="role"][value="Customer"]').check()
    cy.get('[id="register_submit"]').click()

    cy.contains('Password and confirm password does not match').should('be.visible')
    cy.url().should('eq', 'http://localhost:3000/register')
    cy.wait(5000)
  })
  /*
  it('TC1-4: valid input', () => {
    cy.get('[name="email"]').type('test@email.com')
    cy.get('[name="password"]').type('123456789')
    cy.get('[name="confirmPassword"]').type('123456789')
    cy.get('[name="firstName"]').type('firstname')
    cy.get('[name="lastName"]').type('lastname')
    cy.get('[name="displayName"]').type('displayname')
    cy.get('[name="phoneNumber"]').type('0000000000')
    cy.get('[name="birthDate"]').type('2000-02-20')
    cy.get('[name="gender"][value="Male"]').check()
    cy.get('[name="role"][value="Customer"]').check()
    cy.get('[id="register_submit"]').click()

    cy.url().should('eq', 'http://localhost:3000/verify')
    cy.wait(5000)
  })
  */
  it('S1: exist email', () => {
    cy.get('[name="email"]').type('provider@test.gg')
    cy.get('[name="password"]').type('12345678')
    cy.get('[name="confirmPassword"]').type('12345678')
    cy.get('[name="firstName"]').type('firstname')
    cy.get('[name="lastName"]').type('lastname')
    cy.get('[name="displayName"]').type('displayname')
    cy.get('[name="phoneNumber"]').type('0000000000')
    cy.get('[name="birthDate"]').type('2000-02-20')
    cy.get('[name="gender"][value="Male"]').check()
    cy.get('[name="role"][value="Customer"]').check()
    cy.get('[id="register_submit"]').click()

    cy.contains('This email is already used!').should('be.visible')
    cy.url().should('eq', 'http://localhost:3000/register')
    cy.wait(5000)
  })
})