version: '1.0'
services:
  frontend:
    image: horhub-frontend
    build: ./frontend
    container_name: frontend
    expose:
      - "3000"
    ports:
      - "3000:3000"
  backend:
    image: horhub-backend
    build: ./backend
    container_name: backend
    expose:
      - "3001"
    ports:
      - "3001:3001"